# Generated by Django 5.0.4 on 2024-04-26 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traiter',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='chef_agence',
            name='agence',
        ),
        migrations.AlterField(
            model_name='demande',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.utilisateur'),
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='titre',
            new_name='libelle',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='nom',
            new_name='libelle',
        ),
        migrations.AddField(
            model_name='traiter',
            name='utilisateur',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='support.utilisateur'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='agence',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='support.agence'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='contact',
            field=models.CharField(default=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.section'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Chef_Agence',
        ),
    ]
