# Generated by Django 5.0.6 on 2024-05-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_demandes', to='support.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.agence'),
        ),
    ]
