# Generated by Django 5.0.6 on 2024-05-23 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_service_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_formulation',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 11, 54, 9, 169753, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messagedemande',
            name='date_envoi',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 11, 54, 9, 201284, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date_notification',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 11, 54, 9, 201284, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='traiter',
            name='date_traitement',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 11, 54, 9, 201284, tzinfo=datetime.timezone.utc)),
        ),
    ]
